name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Cache emsdk
      uses: actions/cache@v1
      id: cache # This is important!
      with:
        # Set to the same folder as actions-cache-folder (more below)
        path: 'emsdk-cache'
        # Set the end bit to emsdk version
        key: ${{ runner.os }}-emsdk-1.38.40

    - name: Setup emsdk (use cache if found, create otherwise)
      uses: mymindstorm/setup-emsdk@v2
      with:
        # Make sure to set a version number!
        version: 1.38.40
        # This is the name of the cache folder.
        # The cache folder will be placed in the build directory,
        #  so make sure it doesn't conflict with anything!
        actions-cache-folder: 'emsdk-cache'
        # This stops it from using tc.cacheDir since we are using
        #  actions/cache.
        no-cache: true

    - name: Verify
      run: emcc -v
    - name: git
      env: CXX=emcc
      run: |
        git clone https://github.com/ArduPilot/ardupilot.git --depth 2
        cd ardupilot
        git submodule init
        git submodule update
        emconfigure sh -c './waf configure'
        emmake ./waf
      
